spring.application.name=documentsSystem

spring.datasource.url=jdbc:postgresql://postgres:5432/documents
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


aws.s3.bucket=${AWS_BUCKET}
aws.region=${AWS_REGION}



jwt.secret=Z0WIsJlN8+2iK39e1M1qS2e112qIn8wfQ7n3jg2Qv9s=
jwt.expiration=3600000
