spring.application.name=documentsSystem

spring.datasource.url=jdbc:postgresql://postgres:5432/documents
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

aws.accessKey=${AWS_ACCESS_KEY}
aws.secretKey=${AWS_SECRET_KEY}
aws.region=eu-north-1
aws.s3.bucket=sap-s3-proj-buck



jwt.secret=lIsIJc2JGvL0hZdh3813+juR86M2lEoBfrn/75cQD7E=
jwt.expiration=3600000