spring.application.name=documentsSystem

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


aws.s3.bucket=${AWS_BUCKET}
aws.region=${AWS_REGION}



jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
