ALTER TABLE users ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE document_versions ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE documents ADD COLUMN version BIGINT NOT NULL DEFAULT 0;